language: node_js

env:
  CODECLIMATE_REPO_TOKEN: bf670fe192fdc64141c8e6c29042ee4e7337753465252d73f78e27a59cbc037d

addons:
  code_climate:
    repo_token: bf670fe192fdc64141c8e6c29042ee4e7337753465252d73f78e27a59cbc037d

before_script:
  - npm install -g istanbul

after_success:
  - npm install -g codeclimate-test-reporter
  - istanbul cover node_modules/.bin/_mocha
  - codeclimate-test-reporter < coverage/lcov.info
